import pygame
import sys
import math
from os import path


FPS = 120
LIGHTGRAY = (100, 100, 100)
BLOCK_SIZE = 50

# 2. WINDOW
RESOLUTION_X = 500
RESOLUTION_Y = 500
WINDOW_SIZE = (RESOLUTION_X, RESOLUTION_Y)

# 3. SCREEN
SCREEN_WIDTH = RESOLUTION_X
SCREEN_HEIGHT = RESOLUTION_Y
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)


start = 0
end = 0